version: "3.8"
services:
  puppet-server:
    build: docker/server
    working_dir: /opt/tamakiii-sandbox/hello-puppet
    volumes:
      - .:/opt/tamakiii-sandbox/hello-puppet

  puppet-client:
    build: docker/client
